/* This file is generated by scripts/generate-federal-policy.mts. Do not edit manually. */

export const FEDERAL_CENSUS_DATA = Object.freeze({
  "effectiveCongress": Object.freeze({
    "first": 118,
    "last": 119
  }),
  "votingStates": Object.freeze([
    Object.freeze({
      "code": "AL",
      "fips": "01",
      "representativeCount": 7
    }),
    Object.freeze({
      "code": "AK",
      "fips": "02",
      "representativeCount": 1
    }),
    Object.freeze({
      "code": "AZ",
      "fips": "04",
      "representativeCount": 9
    }),
    Object.freeze({
      "code": "AR",
      "fips": "05",
      "representativeCount": 4
    }),
    Object.freeze({
      "code": "CA",
      "fips": "06",
      "representativeCount": 52
    }),
    Object.freeze({
      "code": "CO",
      "fips": "08",
      "representativeCount": 8
    }),
    Object.freeze({
      "code": "CT",
      "fips": "09",
      "representativeCount": 5
    }),
    Object.freeze({
      "code": "DE",
      "fips": "10",
      "representativeCount": 1
    }),
    Object.freeze({
      "code": "FL",
      "fips": "12",
      "representativeCount": 28
    }),
    Object.freeze({
      "code": "GA",
      "fips": "13",
      "representativeCount": 14
    }),
    Object.freeze({
      "code": "HI",
      "fips": "15",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "ID",
      "fips": "16",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "IL",
      "fips": "17",
      "representativeCount": 17
    }),
    Object.freeze({
      "code": "IN",
      "fips": "18",
      "representativeCount": 9
    }),
    Object.freeze({
      "code": "IA",
      "fips": "19",
      "representativeCount": 4
    }),
    Object.freeze({
      "code": "KS",
      "fips": "20",
      "representativeCount": 4
    }),
    Object.freeze({
      "code": "KY",
      "fips": "21",
      "representativeCount": 6
    }),
    Object.freeze({
      "code": "LA",
      "fips": "22",
      "representativeCount": 6
    }),
    Object.freeze({
      "code": "ME",
      "fips": "23",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "MD",
      "fips": "24",
      "representativeCount": 8
    }),
    Object.freeze({
      "code": "MA",
      "fips": "25",
      "representativeCount": 9
    }),
    Object.freeze({
      "code": "MI",
      "fips": "26",
      "representativeCount": 13
    }),
    Object.freeze({
      "code": "MN",
      "fips": "27",
      "representativeCount": 8
    }),
    Object.freeze({
      "code": "MS",
      "fips": "28",
      "representativeCount": 4
    }),
    Object.freeze({
      "code": "MO",
      "fips": "29",
      "representativeCount": 8
    }),
    Object.freeze({
      "code": "MT",
      "fips": "30",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "NE",
      "fips": "31",
      "representativeCount": 3
    }),
    Object.freeze({
      "code": "NV",
      "fips": "32",
      "representativeCount": 4
    }),
    Object.freeze({
      "code": "NH",
      "fips": "33",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "NJ",
      "fips": "34",
      "representativeCount": 12
    }),
    Object.freeze({
      "code": "NM",
      "fips": "35",
      "representativeCount": 3
    }),
    Object.freeze({
      "code": "NY",
      "fips": "36",
      "representativeCount": 26
    }),
    Object.freeze({
      "code": "NC",
      "fips": "37",
      "representativeCount": 14
    }),
    Object.freeze({
      "code": "ND",
      "fips": "38",
      "representativeCount": 1
    }),
    Object.freeze({
      "code": "OH",
      "fips": "39",
      "representativeCount": 15
    }),
    Object.freeze({
      "code": "OK",
      "fips": "40",
      "representativeCount": 5
    }),
    Object.freeze({
      "code": "OR",
      "fips": "41",
      "representativeCount": 6
    }),
    Object.freeze({
      "code": "PA",
      "fips": "42",
      "representativeCount": 17
    }),
    Object.freeze({
      "code": "RI",
      "fips": "44",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "SC",
      "fips": "45",
      "representativeCount": 7
    }),
    Object.freeze({
      "code": "SD",
      "fips": "46",
      "representativeCount": 1
    }),
    Object.freeze({
      "code": "TN",
      "fips": "47",
      "representativeCount": 9
    }),
    Object.freeze({
      "code": "TX",
      "fips": "48",
      "representativeCount": 38
    }),
    Object.freeze({
      "code": "UT",
      "fips": "49",
      "representativeCount": 4
    }),
    Object.freeze({
      "code": "VT",
      "fips": "50",
      "representativeCount": 1
    }),
    Object.freeze({
      "code": "VA",
      "fips": "51",
      "representativeCount": 11
    }),
    Object.freeze({
      "code": "WA",
      "fips": "53",
      "representativeCount": 10
    }),
    Object.freeze({
      "code": "WV",
      "fips": "54",
      "representativeCount": 2
    }),
    Object.freeze({
      "code": "WI",
      "fips": "55",
      "representativeCount": 8
    }),
    Object.freeze({
      "code": "WY",
      "fips": "56",
      "representativeCount": 1
    })
  ]),
  "nonlaunchJurisdictions": Object.freeze([
    "DC",
    "AS",
    "GU",
    "MP",
    "PR",
    "VI"
  ]),
  "nonlaunchJurisdictionFips": Object.freeze({
    "DC": "11",
    "AS": "60",
    "GU": "66",
    "MP": "69",
    "PR": "72",
    "VI": "78"
  }),
  "totalVotingStates": 50,
  "totalRepresentativeCount": 435
} as const);
